### ISSUE TITLE
NoSuchMethodError: The getter 'pointerRouter' was called on null.

### ISSUE THREAD

**Issue by Mirodil** [luanpotter/flame#33]
Hi,
The code `Flame.util.addGestureRecognizer(createTapRecognizer());` throws the following error:
```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The getter 'pointerRouter' was called on null.
Receiver: null
Tried calling: pointerRouter
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Util.addGestureRecognizer (package:flame/util.dart:55:29)
#2      new MatchingGame (package:myapp/main.dart:24:16)
#3      main (package:myapp/main.dart:12:27)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Error -32601 received from application: Method not found
```

The code example:

```dart
class MGame extends BaseGame {
  
  MGame() {
    Flame.util.addGestureRecognizer(createTapRecognizer());
  }

 TapGestureRecognizer createTapRecognizer() {
    return new TapGestureRecognizer()
      ..onTapUp =
          (TapUpDetails details) => this.handleTap(details.globalPosition);
  }

  handleTap(Offset details) {
    // TODO:....
  }
}
```

Am I doing something wrong?

**Comment by Mirodil** [comment]
I found solution I had to call `Flame.initializeWidget();` in the beginning of the program.
